---
title: Ronald Jordan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: amisword@gmail.com
description: I am a died in the wool eclectic learner who has been fortunate to spend
  my life doing what I love most — giving people the tools to help themselves.
baseurl: ''
url: https://rdev.co.za
twitter_username: jron82
github_username: jron82
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
